### ISSUE TITLE
This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 9 exceeded minimum of 10

### ISSUE THREAD

**Issue by FreakOutITGeek** [chrisjshull/homebridge-nest#389]
I am receiving the following error:
"[24/03/2021, 16:02:04] [homebridge-nest] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 9 exceeded minimum of 10. See https://git.io/JtMGR for more info."

My minimum/away temperature on my thermostat is 9 and this appears to be causing issues.

$ node --version
v14.16.0
$ homebridge --version
Initializing HAP-NodeJS v0.9.4...
1.3.4

**Comment by xortuna** [comment]
I assume you have an EU NEST model?
I also had the same issue, 
I edited line 73 in https://github.com/chrisjshull/homebridge-nest/blob/master/lib/nest-thermostat-accessory.js#L73
and set this to 9, mine works now without problems.

**Comment by mvaneijgen** [comment]
@xortuna doesn't get overwritten each time the plugin updates?

**Comment by xortuna** [comment]
Unfortunately yes.

It would need this exposed to config.json for a more permanent fix.
Problem is EU nests don't have AC cooling - nest instead sets the target temperature to 9 when inactive, which spams the above error message in the plugin.

**Comment by hugo-leij** [comment]
Thnx @xortuna 
I had the same issue. I manually adjust it and it works :D. Would be nice if this can be set in the pulgin

**Comment by Lazybeez** [comment]
why not using `this.device.can_cool` to determine the minimum set temperature limit as 9 or 10? could `this.device.can_cool` return what we need? or we just simply want to limit user from doing so

**Comment by cjattard** [comment]
just want to add another +1 to have this manually set in the plugin in a future version. 

Same story as above - European setup nest (uk market)

This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 4.5 exceeded minimum of 10. See https://git.io/JtMGR for more info

thanks

**Comment by jacklawry** [comment]
I also have this same issue but I have just set the echo temp to 10ºC in the settings for each thermostat instead of the default 9ºC and the errors also stop without any code changes. If it's 10ºC in my house I will want the heating on anyway!

**Comment by EjvindHald** [comment]
This is also a problem for the US model thermostat. 
I have several of these and I am only using these to control heat. There is no wire connected to control cooling, and the thermostat very nicely recognize this and adapts. However, it sends default value of 9 degrees Celcius out as cooling temp, and I cannot change that. So the log for Homebridge gets spammed.
The most simple solution would be to permanently change the minimum setting from 10 to 9 degrees in the code as shown in this thread. This would allow the default values without log spamming.
@adriancable will you consider this?

**Comment by EjvindHald** [comment]
I have now also edited line 73 in https://github.com/chrisjshull/homebridge-nest/blob/master/lib/nest-thermostat-accessory.js#L73 and set this to 9, which stops the spamming of the log. I am running Homebridge in Docker, and it is actually quite easy to change using Terminal in homebridge-config-ui-x and then nano editor to simply change from 10 to 9.

It will be overwritten with next version, but I hope @adriancable will change this permanently.

**Comment by adriancable** [comment]
@EjvindHald - no, the change you suggest replaces a completely harmless warning with broken behaviour.

The minimum on line 73 of 10 degrees C is correct, because 10 degrees C is the lowest temperature the thermostat can manually be set to. If you change that to 9, then it allows the user to set the temperature to 9 degrees C from HomeKit, which will be rejected by the thermostat, resulting in situations where the thermostat will seem to 'ignore' user-initiated temperature changes.

I know that people don't like seeing the warnings, and maybe Homebridge will decide in future to have an option to turn them off, but please understand that the warning in this case does not mean that anything is wrong, and does not mean that any code change is necessary. (And indeed, I do not believe it is possible to change the code my side so the warning doesn't appear, without breaking the thermostat set function.)

**Comment by adriancable** [comment]
To be absolutely clear: *the correct solution here is to ignore the warning. It is just a consequence of a quirk of the way Nest works. It does not mean anything is wrong.*

If you really don't like the warning, then you can do what @jacklawry suggests.

@xortuna, @hugo-leij, @cjattard etc. - sorry but changing the code in the way you suggest breaks things when you try to set the temperature as I explain above. So, I will not be changing the code.

**Comment by EjvindHald** [comment]
@adriancable : thank you very much for your effort and detailed explanation - it is highly appreciated.
I do understand, that it is a false positive and there is no real error behind this log message. However, I have 9 thermostats, and these generates more than 1,000 lines in the log every day. This makes it hard to spot a real error, if it occurs. That is the reason I would like to remove these false positives.

I am not using Eco mode, but I have turned it on, changed minimum to 10 degrees and turned the Eco mode off again, so it suit my needs. However, that gives a false positive message saying that 4.5 degrees exceed the minimum temp. The value 4.5 degrees is the default safety temperature. My message is identical to the one reported by @cjattard previously in this thread.

You can leave it as it is - I will live with it.

**Comment by adriancable** [comment]
@EjvindHald - thanks. I do agree the message is annoying! Unfortunately, the message is produced by Homebridge itself (not homebridge-nest) and, as far as I know, there isn't any way to disable those warnings.

**Comment by xortuna** [comment]
Hi Adrian,
On EU nest models 9 degrees is a valid and settable temperature, both in HomeKit and on the device itself
Video for reference (here I’ve modified HomeKit-Nest with the above change)

https://youtube.com/shorts/VJzTmT8ld2o

**Comment by adriancable** [comment]
@xortuna - wow - if you hadn't sent a video I wouldn't have believed it!

I am wondering whether the 9-degree lower limit is specific to EU thermostats, or whether it is something that has been changed (down from 10) in all degrees-C regions, possibly in a relatively recent software update.

Could anyone in a degrees-C (but non-EU) country confirm what the lower temperature limit is on the thermostat itself, both in heat and in cool mode?

**Comment by jacklawry** [comment]
Yes 9°C is valid in UK (and the default). 

Eco can be set to 4.5°C as attached. 

![image](https://user-images.githubusercontent.com/3786136/129808765-913bf232-e858-4882-b412-44a4dcc9b22e.png)

**Comment by EjvindHald** [comment]
On the US thermostat model, I can confirm that 9 degrees is a valid lower setting for heating. 
I do not know for cooling, as this is not wired in my setup.

**Comment by adriancable** [comment]
Fixed in 4.6.0.

**Comment by qerim** [comment]
@adriancable 

I am still seeing this in latest `v4.6.9` version. I cannot see a setting in the Config to disabled this for EU version.
