### ISSUE TITLE
Errors after updates to plugin and Homebridge

### ISSUE THREAD

**Issue by beslergr** [chrisjshull/homebridge-nest#512]
**Describe the bug**
Receiving the following errors:

[15/02/2022, 01:15:37] [Nest] Access token acquisition via googleAuth failed (code ECONNRESET).
[15/02/2022, 01:15:37] [Nest] Unable to authenticate with Google/Nest.
[15/02/2022, 01:15:37] [Nest] NOTE: Because we couldn't connect to the Nest service, your Nest devices in HomeKit will not be responsive.

**To Reproduce**
1. Updated Homebridge Nest to v 4.6.4 and Homebridge to 1.4.0. No longer authenticates correctly through Nest, Google Token or Google Cookie.

**Expected behavior**

Include with your bug report this version info:
```sh
node --version 14.16.1
homebridge --version 1.4.0
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by jdgorelick** [comment]
I'm having the same issue. It will eventually get stuck on temperature readings and settings from my thermostats and temperature sensors that do not match the current state.

**Comment by adriancable** [comment]
@jdgorelick - any chance of some logs (along with what version of the plug-in you are using) so I can troubleshoot?

**Comment by adriancable** [comment]
@beslergr - ECONNRESET is an issue with your Internet provider, your router or the device you are running Homebridge on., Not a plug-in or Nest issue.

**Comment by adriancable** [comment]
Closing since inactive, and pretty sure @jdgorelick 's issue would have been fixed by 4.6.5.

**Comment by beslergr** [comment]
Having this problem again. Using plugin version 4.6.5. Getting an "unable to authenticate with Nest" message on every authentication method. Was working for a short period, but error came back with recent HomeBridge restart. Same error messages as original post.

Not sure what would be causing this on the ISP or router end of things. Using a standard config of Xfinity internet + Google wifi + Raspberry Pi.  How can I further debug this? Pretty frustrating, especially when things sometimes DO work.

**Comment by adriancable** [comment]
If you are still getting an ECONNRESET error during auth (as per your original post), it means that something between your machine and Google’s server is dropping the connection in the middle of the auth call.

Troubleshooting is a usual case of excluding things.

Exclude Xfinity as a cause by connecting to a phone’s tethered Wi-Fi network.

Exclude Google Wi-Fi as a cause by connecting Raspberry Pi direct to your Xfinity modem by Ethernet.

Exclude Raspberry Pi as a cause by trying Homebridge on a Mac or PC.

Sorry, there are no magic bullets. You just have to figure out how to exclude each potential cause (like the 3 examples above) until you figure out where the problem is.
